### ISSUE TITLE
Ho to compile with espeasy-mega from 20181027

### ISSUE THREAD

**Issue by ozett** [djcysmic/NeopixelBusFX#4]
i am not sure how to get your plugin compiled into the actual source?
maybe not even at all?

i compiled myself the actual espeasy mega 20181027 source succesfull.
i put your plugin.ino into the src-folder, compiled again and it was not visible.

i activated the compile of all testing-plugins in ESPeasy_globals.h,
but that did not help. 

i did not find your plugin in the gui under devices.

maybe i am totally off the track. 😕 
you have a hint for me?

thanks a lot.

**Comment by ozett** [comment]
i think now that there is an new #define missing:

#ifdef PLUGIN_BUILD_TESTING

see: https://www.letscontrolit.com/wiki/index.php/ESPEasyDevelopmentGuidelines#Adding_plugins_to_the_master_repostory

maybe you could update your source? if i am right?

----
i doubt, if this is really necessary...  😖

**Comment by ozett** [comment]
i found it: https://github.com/letscontrolit/ESPEasy/issues/1971#issuecomment-433628742

**Comment by djcysmic** [comment]
Yes, you're right. It is already in the define_plugin_sets.h experimental branch - there you can put it into the stable or testing branch, if you want to.

**Comment by ozett** [comment]
😸  thankx
