### ISSUE TITLE
compile error: P124_NeoPixelBusFX:1027: error: new declaration 'uint32_t Wheel(uint8_t)'

### ISSUE THREAD

**Issue by ozett** [djcysmic/NeopixelBusFX#5]
i installed the neopixel-lib verseion 2.3.4 from makuna within the arduini-ide.

but i now get this compile-error on the espeasymega 20181027 source:

``
P124_NeoPixelBusFX:1027: error: new declaration 'uint32_t Wheel(uint8_t)'
``

![image](https://user-images.githubusercontent.com/5937811/47606093-b3c1fe80-da0f-11e8-98f2-2cbc9ef9af6e.png)

any hints to resove this issue?

thanks, 👍

**Comment by djcysmic** [comment]
It seems to be a double named declaration "Wheel" in NeopixelBusFX and Candle - but I don't know any version of Candle, where a declaration "Wheel" exists...

**Comment by ozett** [comment]
your are right, in the original plugin there is no "wheel"
->https://github.com/letscontrolit/ESPEasy/blob/mega/src/_P042_Candle.ino

i found a patched version in the forum:
-> https://www.letscontrolit.com/forum/viewtopic.php?p=27886#p27886

which i used. you can change nr of leds in the web-gui.
this version has a "wheel"-keyword ... 

i will look, if i change the patched version..

i gave the link to the patched version to the espeasy-devs, 
so they can see if they merge the patch into the original version
.> https://github.com/letscontrolit/ESPEasy/issues/1888

not done today...

**Comment by ozett** [comment]
i changed the naming for "Wheel" into "WheelRain" in the patched P042-candle source.
(is it a ... :con ..function? ..i am no coder... 😭 ),
it compiled ok. i will test.

![image](https://user-images.githubusercontent.com/5937811/47608429-e1b63b80-da2d-11e8-9b89-381246e267c1.png)

**Comment by ozett** [comment]
it worked.
in the patched candle pluin 042 there is the same "Wheel" name in the rainbow-effect.
Renaming helped. Now it stays open if the developers of ESPeasy transfer the patch in the stable tree, and if theykeep or change the name to integrate your plugin 124 without conficts too. 

i leave the track here.
