### ISSUE TITLE
update doku on .md with defaults

### ISSUE THREAD

**Issue by ozett** [djcysmic/NeopixelBusFX#8]
very helpful to know, that there are defaults for every effekt.
you should  try to update the landing page here ?

https://forum.fhem.de/index.php/topic,73949.msg847764.html#msg847764

**Comment by djcysmic** [comment]
Done.

**Comment by ozett** [comment]
👍 
just one last thing: 
as a newbee it is helpful to know, that you can call every cmd without values.
maybe you should mention this explicitly like:

List of commands:
if you call a command without values, the defaults of the cmd are used.

Example:
```
nfx kitt color [speed]
o speed +/- 0-50, default: 25
```

shortest form of the cmd without any certain value:
```nfx kitt```
than the cmd is executed with default values like 
```nfx kitt ff0000 25```

**Comment by ozett** [comment]
and a second last thing:
on the kitt-cmd there is no default value  for color, 
if you omit this, the lights stay off=black.

maybe an idea to put in "kitt" also a default color?
